config/routes.rb
Rails.application.routes.draw do
 

  get 'welcome/index'
  get "logout" => 'session#destroy', :as => 'logout'
  get "login" => 'session#new', :as => 'login'
  get "signup" => 'users#new', :as => 'signup'

  resources :articles, :users, :session
  root 'welcome#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
	validates :title,
		presence: true,
		length: {minimum: 5}

end

app/models/users.rb
class Users < ActiveRecord::Base
	
	email_regex = /\b[A-Z0-9._%a-z\-]+@(?:[A-Z0-9a-z\-]+\.)+[A-Za-z]{2,4}\z/
	validates :firstName,	presence: true
	validates :lastName,	presence: true
	validates :emailAddr,		presence: true,
							:format => {:with => email_regex},
							:uniqueness => {:case_sensitive => false}
	validates :username,	presence: true
	validates :password,	presence: true

	before_save :encrypt_password

	def has_password?(submitted_password)
		encrypt_password = encrypt(submitted_password)
	end

	def self_authenticate(email, submitted_password)
		user = find_by_email(email)

		return nil if user.nil?
		return user if user.password_hash = BCrypt::Engine.hash_secret(submitted_password, user.password_salt)
	end

	private
		def encrypt_password
			self.password_salt = BCrypt::Engine.generate.password_salt
			self.password_hash = BCrypt::Engine.hash_secret(submitted_password, password_salt)
		end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

 helper_method :current_user
 private

 def current_user
 	@current_user ||= User.find(session[:user_id]) if session[:user_id]
 	
 end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

	def new
	end

	def create
		@article = Article.new(article_params)
 
  		@article.save
  		redirect_to @article
	end

	def show
		@article = Article.find(params[:id])
	end

	def index
	  @articles = Article.all
	end

	private
		def article_params
			params.require(:article).permit(:title, :text, :created_at)
		end

end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
  	user = User.authenticate(params[:email], params[:password])
  	if user
  		session[:user_id] = user.id
  		redirect_to root_url, :notice => "Logged In"
  	else
  		flash.now.alert = "Incorrect Password"
  		render action: new
    end
  end

def destroy
	session[:user_id,] = nil
	redirect_to root_url, :notice => "Logged Out"	
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = Users.new	
  end
 	
 def create
 	@user = Users.new(params[:user])
  	if @user.save
   		redirect_to root_url, notice: 'User created'
   	else
   		render action: new
 	end
 end

 def show
 	@user = Users.find(params[:user_id])
 end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/index.html.erb
<h1>Listing articles</h1>
 <%= link_to 'New article', new_article_path %>
 <%= link_to 'Sign Up', new_user_path %>
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th>Created On:</th>
  </tr>
 
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= article.created_at %></td>
    
    </tr>
  <% end %>
</table>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= form_for :article, url: articles_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>


 
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p>
	<strong>Title:</strong>
	<%= @article.title %>
</p>
<p>
	<strong>Text:</strong>
	<%= @article.text %>
</p>
<p>
	<strong>Submitted By:</strong>
</p>


<%= link_to 'Back', articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="user_nav">
  <% if current_user %>
    Logged in as <%= current_user.email %>.
    <%= link_to "Log out", logout_path %>
  <% else %>
    <%= link_to "Sign up", signup_path %> or
    <%= link_to "log in", login_path %>
  <% end %>
</div>

<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, :user_id => "flash_#{name}" %>
<% end %>
<%= yield %>

</body>
</html>

app/views/session/new.html.erb
<h1>Log in</h1>

<%= form_tag session_path do %>
  <p>
    <%= label_tag :email %><br />
    <%= text_field_tag :email, params[:email] %>
  </p>
  <p>
    <%= label_tag :password %><br />
    <%= password_field_tag :password %>
  </p>
  <p class="button"><%= submit_tag "Log in" %></p>
<% end %>

app/views/users/login.html.erb
 <h1>Log In!</h1> 
<%= form_for :user, url: login_path do |user| %>
  <p>
    <%= user.label :username %><br>
    <%= user.text_field :username %>
  </p>
 
  <p>
    <%= user.label :password %><br>
    <%= user.text_area :password %>
  </p>

  <p>
    <%= user.submit %>
  </p>
<% end %>

<%= link_to 'Back', root_path %>

app/views/users/new.html.erb
<h1>Sign Up!</h1>
<p>Find me in app/views/users/new.html.erb</p>

<%= simple_form_for @user, url: signup_path do |f| %>
  <%= f.input :firstName %>
  <%= f.input :lastName %>
  <%= f.input :emailAddr %>
  <%= f.input :uname %>
  <%= f.password_field :pword %>
  <%= f.submit :submit %>
<% end %>


<%= link_to 'Back', root_path %>

app/views/users/show.html.erb
<p>
	<strong>Username:</strong>
	<%= @user.uname %>
</p>
<p>
	<strong>First Name:</strong>
	<%= @user.firstName %>
</p>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>
<%= link_to 'My Blog', controller: 'articles' %>
<%= link_to 'Log In', login_path %>
<%= link_to 'Sign Up', new_user_path %>